# Error codes and descriptions
text.001=Requestor Reference ID is missing
text.002=Country Code is missing
text.003=IC Number is missing
text.004=Expiry Date is missing
text.005=DTP Customer ID is missing
text.006=Deal Reference No is missing
text.007=Beneficiary Name is missing
text.008=Applicant Name is missing
text.009=LC Amount is missing
text.010=Currency is missing
text.011=Amount is missing
text.012=Version Number is missing
text.013=Customer Instructions are missing
text.014=Charge Debit Account Number is missing
text.015=Charge Debit Account Currency is missing
text.016=Presentation Currency is missing
text.017=Presentation Amount is missing
text.018=Document Check Required is missing
text.019=Applicant Related Party is missing
text.020=Settlement Instruction Code is missing
text.021=Discrepancy Type Code is missing
text.022=Disbursement Account No is missing
text.023=Disbursement Account Currency is missing
text.024=Use Export Bills Proceeds is missing
text.025=Upload Method Code is missing
text.026=Available Balance is missing
text.027=LC Available Balance Currency is missing
text.028=LC Available Balance Amount is missing
text.029=Issuing Bank LC Ref No is missing
text.030=Your Reference is missing
text.031=Deal ID is missing
text.032=Step Code is missing
text.033=Step No is missing
